# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
# Author : KimJihong190
# Author info : https://github.com/KimJiHong190
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QApplication, QMainWindow, QTextEdit
from PyQt5 import QtCore, QtGui, QtWidgets
import os

class NoTabTextEdit(QtWidgets.QTextEdit):
    """Custom QTextEdit that ignores the Tab key."""

    def keyPressEvent(self, event):
        if event.key() == QtCore.Qt.Key_Tab:
            event.ignore()
        else:
            super().keyPressEvent(event)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1357, 549)
        MainWindow.setMinimumSize(1357, 549)
        MainWindow.setMinimumSize(1357, 549)
        MainWindow.setStyleSheet("""
        QPushButton#styleGroup1, QPushButton#styleGroup2, QPushButton#styleGroup3 {
            background-color: #646262;  /* Default background color, change per group as needed */
            color: #FFFFFF;  /* White text */
            border: 1px solid #000;  /* Black border */
            border-radius: 5px;
            padding: 5px;
            font-weight: bold;
            
        }

        QPushButton#styleGroup1:hover, QPushButton#styleGroup2:hover, QPushButton#styleGroup3:hover {
            background-color: #6e6c6c;  /* Slightly lighter gray on hover, customize per group */
            border: 1px solid #FFF;  /* White border to indicate hover */
            
        }

        QPushButton#styleGroup1:pressed, QPushButton#styleGroup2:pressed, QPushButton#styleGroup3:pressed {
            
            border: 1px solid #000;  /* Optionally change the border color on press */
        }
        
        QPushButton#styleGroup4 {
            background-color: #bbbbbb;
            color: #000000;
            border: 1px solid #000;
            border-radius: 5px;
            padding: 5px;
        }
        
        QPushButton#styleGroup4:hover {
            background-color: #c4c4c4;
            border: 1px solid #FFF;

        }
        QPushButton#styleGroup4:pressed {
            border: 1px solid #000;
        }
        
        QPushButton#styleGroup5 {
            background-color: #e9e9e9;
            color: #000000;
            border: 1px solid #000;
            border-radius: 5px;
            padding: 5px;
        }
        
        QPushButton#styleGroup5:hover {
            background-color: #c4c4c4;
            border: 1px solid #FFF;

        }
        QPushButton#styleGroup5:pressed {
            border: 1px solid #000;
        }
        

        
        QPushButton#styleGroup6 {
            background-color: #ff0000;
            color: #ff0000;
            border-radius: 20px;
        }
        QPushButton#styleGroup6:hover {
            background-color: #ff0000;
            border: 1px solid #FFF;
        }
        QPushButton#styleGroup6:pressed {
            background-color: #ff0000;
            border: 1px solid #000;
        }
        """)
        current_dir = os.path.dirname(os.path.realpath(__file__))
        icons_dir = os.path.join(current_dir, 'feather/icons')

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QFrame(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 2, 1351, 44))
        self.title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title.setObjectName("title")
        self.title_label = QtWidgets.QLabel(self.title)
        self.title_label.setGeometry(QtCore.QRect(530, 10, 24, 24))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(14)
        self.title_label.setFont(font)
        self.title_label.setText("")
        
        airplay_icon_path = os.path.join(icons_dir, "airplay.svg")
        self.title_label.setPixmap(QtGui.QPixmap(airplay_icon_path))
        self.title_label.setObjectName("title_label")
        self.robot_controller_ui_title_label = QtWidgets.QLabel(self.title)
        self.robot_controller_ui_title_label.setGeometry(QtCore.QRect(560, 10, 196, 24))
        self.robot_controller_ui_title_label.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.robot_controller_ui_title_label.setFont(font)
        self.robot_controller_ui_title_label.setObjectName("robot_controller_ui_title_label")
        self.setting_largeframe = QtWidgets.QFrame(self.centralwidget)
        self.setting_largeframe.setGeometry(QtCore.QRect(0, 50, 241, 341))
        self.setting_largeframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setting_largeframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.setting_largeframe.setObjectName("setting_largeframe")
        self.activation_frame = QtWidgets.QFrame(self.setting_largeframe)
        self.activation_frame.setGeometry(QtCore.QRect(1, 1, 239, 91))
        self.activation_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.activation_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.activation_frame.setObjectName("activation_frame")
        
        self.activation_robot2_button = QtWidgets.QPushButton(self.activation_frame)
        self.activation_robot2_button.setGeometry(QtCore.QRect(10, 60, 106, 23))
        self.activation_robot2_button.setObjectName("styleGroup1")
        self.activation_robot2_button.setProperty("state","default")
        self.activation_robot2_button.clicked.connect(lambda: self.toggleButtonStyle(self.activation_robot2_button))

        self.activation_joint_button = QtWidgets.QPushButton(self.activation_frame)
        self.activation_joint_button.setGeometry(QtCore.QRect(124, 60, 106, 23))
        self.activation_joint_button.setObjectName("styleGroup1")
        self.activation_joint_button.setProperty("state","default")
        self.activation_joint_button.clicked.connect(lambda: self.toggleButtonStyle(self.activation_joint_button))
        
        self.activation_all_button = QtWidgets.QPushButton(self.activation_frame)
        self.activation_all_button.setGeometry(QtCore.QRect(10, 30, 220, 23))
        self.activation_all_button.setObjectName("styleGroup1")
        self.activation_all_button.setProperty("state","default")
        self.activation_all_button.clicked.connect(lambda: self.toggleButtonStyle(self.activation_all_button))        

        self.activation_label = QtWidgets.QLabel(self.activation_frame)
        self.activation_label.setGeometry(QtCore.QRect(10, 5, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.activation_label.setFont(font)
        self.activation_label.setObjectName("activation_label")
        self.calibration_frame = QtWidgets.QFrame(self.setting_largeframe)
        self.calibration_frame.setGeometry(QtCore.QRect(1, 92, 239, 91))
        self.calibration_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calibration_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calibration_frame.setObjectName("calibration_frame")
        
        self.calibration_wheel_button = QtWidgets.QPushButton(self.calibration_frame)
        self.calibration_wheel_button.setGeometry(QtCore.QRect(10, 60, 69, 23))
        self.calibration_wheel_button.setObjectName("styleGroup1")
        self.calibration_wheel_button.setProperty("state","default")
        self.calibration_wheel_button.clicked.connect(lambda: self.toggleButtonStyle(self.calibration_wheel_button))            
        
        self.calibration_joint_button = QtWidgets.QPushButton(self.calibration_frame)
        self.calibration_joint_button.setGeometry(QtCore.QRect(160, 60, 69, 23))
        self.calibration_joint_button.setObjectName("styleGroup1")
        self.calibration_joint_button.setProperty("state","default")
        self.calibration_joint_button.clicked.connect(lambda: self.toggleButtonStyle(self.calibration_joint_button))    
        
        self.calibration_robot2_button = QtWidgets.QPushButton(self.calibration_frame)
        self.calibration_robot2_button.setGeometry(QtCore.QRect(85, 60, 69, 23))
        self.calibration_robot2_button.setObjectName("styleGroup1")
        self.calibration_robot2_button.setProperty("state","default")
        self.calibration_robot2_button.clicked.connect(lambda: self.toggleButtonStyle(self.calibration_robot2_button))    
        
        self.calibration_all_button = QtWidgets.QPushButton(self.calibration_frame)
        self.calibration_all_button.setGeometry(QtCore.QRect(10, 30, 220, 23))
        self.calibration_all_button.setObjectName("styleGroup1")
        self.calibration_all_button.setProperty("state","default")
        self.calibration_all_button.clicked.connect(lambda: self.toggleButtonStyle(self.calibration_all_button))    
        
        self.calibration_label = QtWidgets.QLabel(self.calibration_frame)
        self.calibration_label.setGeometry(QtCore.QRect(10, 5, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.calibration_label.setFont(font)
        self.calibration_label.setObjectName("calibration_label")
        self.robot2_control_frame = QtWidgets.QFrame(self.setting_largeframe)
        self.robot2_control_frame.setGeometry(QtCore.QRect(1, 183, 239, 161))
        self.robot2_control_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.robot2_control_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.robot2_control_frame.setObjectName("robot2_control_frame")
        self.robot2_control_label = QtWidgets.QLabel(self.robot2_control_frame)
        self.robot2_control_label.setGeometry(QtCore.QRect(10, 5, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.robot2_control_label.setFont(font)
        self.robot2_control_label.setObjectName("robot2_control_label")
        self.robot2_control_both_frame = QtWidgets.QFrame(self.robot2_control_frame)
        self.robot2_control_both_frame.setGeometry(QtCore.QRect(10, 30, 101, 121))
        self.robot2_control_both_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.robot2_control_both_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.robot2_control_both_frame.setObjectName("robot2_control_both_frame")
        self.robot2_control_both_label = QtWidgets.QLabel(self.robot2_control_both_frame)
        self.robot2_control_both_label.setGeometry(QtCore.QRect(6, 6, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.robot2_control_both_label.setFont(font)
        self.robot2_control_both_label.setObjectName("robot2_control_both_label")
        
        self.robot2_control_both_up_arrow_button = QtWidgets.QPushButton(self.robot2_control_both_frame)
        self.robot2_control_both_up_arrow_button.setGeometry(QtCore.QRect(10, 40, 31, 31))
        self.robot2_control_both_up_arrow_button.setText("")
        
        # icon icon icon icon
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(icons_dir,"arrow-up.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.robot2_control_both_up_arrow_button.setIcon(icon)
        
        
        self.robot2_control_both_up_arrow_button.setObjectName("robot2_control_both_up_arrow_button")
        self.robot2_control_both_up_arrow_button.setObjectName("styleGroup1")
        self.robot2_control_both_up_arrow_button.setProperty("state","default")
        self.robot2_control_both_up_arrow_button.clicked.connect(lambda: self.toggleButtonStyle(self.robot2_control_both_up_arrow_button))          
        
        self.robot2_control_both_down_arrow_button = QtWidgets.QPushButton(self.robot2_control_both_frame)
        self.robot2_control_both_down_arrow_button.setGeometry(QtCore.QRect(10, 80, 31, 31))
        self.robot2_control_both_down_arrow_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(icons_dir,"arrow-down.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.robot2_control_both_down_arrow_button.setIcon(icon1)
        self.robot2_control_both_down_arrow_button.setObjectName("robot2_control_both_down_arrow_button")
        self.robot2_control_both_down_arrow_button.setObjectName("styleGroup1")
        self.robot2_control_both_down_arrow_button.setProperty("state","default")
        self.robot2_control_both_down_arrow_button.clicked.connect(lambda: self.toggleButtonStyle(self.robot2_control_both_down_arrow_button))          
        

        self.robot2_control_both_right_arrow_button = QtWidgets.QPushButton(self.robot2_control_both_frame)
        self.robot2_control_both_right_arrow_button.setGeometry(QtCore.QRect(60, 40, 31, 31))
        self.robot2_control_both_right_arrow_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(icons_dir,"arrow-right.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.robot2_control_both_right_arrow_button.setIcon(icon2)
        self.robot2_control_both_right_arrow_button.setObjectName("robot2_control_both_right_arrow_button")
        self.robot2_control_both_right_arrow_button.setObjectName("styleGroup1")
        self.robot2_control_both_right_arrow_button.setProperty("state","default")
        self.robot2_control_both_right_arrow_button.clicked.connect(lambda: self.toggleButtonStyle(self.robot2_control_both_right_arrow_button))  

        
        self.robot2_control_both_left_arrow_button = QtWidgets.QPushButton(self.robot2_control_both_frame)
        self.robot2_control_both_left_arrow_button.setGeometry(QtCore.QRect(60, 80, 31, 31))
        self.robot2_control_both_left_arrow_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(os.path.join(icons_dir,"arrow-left.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.robot2_control_both_left_arrow_button.setIcon(icon3)
        self.robot2_control_both_left_arrow_button.setObjectName("robot2_control_both_left_arrow_button")
        self.robot2_control_both_left_arrow_button.setObjectName("styleGroup1")
        self.robot2_control_both_left_arrow_button.setProperty("state","default")
        self.robot2_control_both_left_arrow_button.clicked.connect(lambda: self.toggleButtonStyle(self.robot2_control_both_left_arrow_button))  

        
        self.robot2_control_left_frame = QtWidgets.QFrame(self.robot2_control_frame)
        self.robot2_control_left_frame.setGeometry(QtCore.QRect(120, 30, 51, 121))
        self.robot2_control_left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.robot2_control_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.robot2_control_left_frame.setObjectName("robot2_control_left_frame")
        self.robot2_control_left_label = QtWidgets.QLabel(self.robot2_control_left_frame)
        self.robot2_control_left_label.setGeometry(QtCore.QRect(6, 6, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.robot2_control_left_label.setFont(font)
        self.robot2_control_left_label.setObjectName("robot2_control_left_label")
        
        self.robot2_control_left_up_arrow_button = QtWidgets.QPushButton(self.robot2_control_left_frame)
        self.robot2_control_left_up_arrow_button.setGeometry(QtCore.QRect(10, 40, 31, 31))
        self.robot2_control_left_up_arrow_button.setText("")
        self.robot2_control_left_up_arrow_button.setIcon(icon)
        self.robot2_control_left_up_arrow_button.setObjectName("robot2_control_left_up_arrow_button")
        self.robot2_control_left_up_arrow_button.setObjectName("styleGroup1")
        self.robot2_control_left_up_arrow_button.setProperty("state","default")
        self.robot2_control_left_up_arrow_button.clicked.connect(lambda: self.toggleButtonStyle(self.robot2_control_left_up_arrow_button))          
        
        self.robot2_control_left_down_arrow_button = QtWidgets.QPushButton(self.robot2_control_left_frame)
        self.robot2_control_left_down_arrow_button.setGeometry(QtCore.QRect(10, 80, 31, 31))
        self.robot2_control_left_down_arrow_button.setText("")
        self.robot2_control_left_down_arrow_button.setIcon(icon1)
        self.robot2_control_left_down_arrow_button.setObjectName("robot2_control_left_down_arrow_button")
        self.robot2_control_left_down_arrow_button.setObjectName("styleGroup1")
        self.robot2_control_left_down_arrow_button.setProperty("state","default")
        self.robot2_control_left_down_arrow_button.clicked.connect(lambda: self.toggleButtonStyle(self.robot2_control_left_down_arrow_button))  
        
        self.robot2_control_right_frame = QtWidgets.QFrame(self.robot2_control_frame)
        self.robot2_control_right_frame.setGeometry(QtCore.QRect(180, 30, 51, 121))
        self.robot2_control_right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.robot2_control_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.robot2_control_right_frame.setObjectName("robot2_control_right_frame")
        self.robot2_control_right_label = QtWidgets.QLabel(self.robot2_control_right_frame)
        self.robot2_control_right_label.setGeometry(QtCore.QRect(6, 6, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.robot2_control_right_label.setFont(font)
        self.robot2_control_right_label.setObjectName("robot2_control_right_label")
        
        self.robot2_control_right_up_arrow_button = QtWidgets.QPushButton(self.robot2_control_right_frame)
        self.robot2_control_right_up_arrow_button.setGeometry(QtCore.QRect(10, 40, 31, 31))
        self.robot2_control_right_up_arrow_button.setText("")
        self.robot2_control_right_up_arrow_button.setIcon(icon)
        self.robot2_control_right_up_arrow_button.setObjectName("robot2_control_right_up_arrow_button")
        self.robot2_control_right_up_arrow_button.setObjectName("styleGroup2")
        self.robot2_control_right_up_arrow_button.setProperty("state","default")
        self.robot2_control_right_up_arrow_button.clicked.connect(lambda: self.toggleButtonStyle(self.robot2_control_right_up_arrow_button)) 
        
        
        self.robot2_control_right_down_arrow_button = QtWidgets.QPushButton(self.robot2_control_right_frame)
        self.robot2_control_right_down_arrow_button.setGeometry(QtCore.QRect(10, 80, 31, 31))
        self.robot2_control_right_down_arrow_button.setText("")
        self.robot2_control_right_down_arrow_button.setIcon(icon1)
        self.robot2_control_right_down_arrow_button.setObjectName("robot2_control_right_down_arrow_button")
        self.robot2_control_right_down_arrow_button.setObjectName("styleGroup2")
        self.robot2_control_right_down_arrow_button.setProperty("state","default")
        self.robot2_control_right_down_arrow_button.clicked.connect(lambda: self.toggleButtonStyle(self.robot2_control_right_down_arrow_button)) 
        
        self.control_mode_remote_large_frame = QtWidgets.QFrame(self.centralwidget)
        self.control_mode_remote_large_frame.setGeometry(QtCore.QRect(240, 50, 491, 341))
        self.control_mode_remote_large_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.control_mode_remote_large_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control_mode_remote_large_frame.setObjectName("control_mode_remote_large_frame")
        self.control_mode_frame = QtWidgets.QFrame(self.control_mode_remote_large_frame)
        self.control_mode_frame.setGeometry(QtCore.QRect(10, 10, 471, 81))
        self.control_mode_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.control_mode_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control_mode_frame.setObjectName("control_mode_frame")
        
        self.land_button = QtWidgets.QPushButton(self.control_mode_frame)
        self.land_button.setGeometry(QtCore.QRect(20, 20, 71, 41))
        self.land_button.setObjectName("land_button")
        self.land_button.setObjectName("styleGroup4")
    
        
        self.stand_button = QtWidgets.QPushButton(self.control_mode_frame)
        self.stand_button.setGeometry(QtCore.QRect(110, 20, 71, 41))
        self.stand_button.setObjectName("stand_button")
        self.stand_button.setObjectName("styleGroup4")
      
        
        self.default_button = QtWidgets.QPushButton(self.control_mode_frame)
        self.default_button.setGeometry(QtCore.QRect(200, 20, 71, 41))
        self.default_button.setObjectName("default_button")
        self.default_button.setObjectName("styleGroup4")
   
        
        self.posture_A_button = QtWidgets.QPushButton(self.control_mode_frame)
        self.posture_A_button.setGeometry(QtCore.QRect(290, 20, 71, 41))
        self.posture_A_button.setObjectName("posture_A_button")
        self.posture_A_button.setObjectName("styleGroup4")
     
        
        self.posture_B_button = QtWidgets.QPushButton(self.control_mode_frame)
        self.posture_B_button.setGeometry(QtCore.QRect(380, 20, 71, 41))
        self.posture_B_button.setObjectName("posture_B_button")
        self.posture_B_button.setObjectName("styleGroup4")
      
        
        ## remote control frame part
        self.robot2_remote_control_frame = QtWidgets.QFrame(self.control_mode_remote_large_frame)
        self.robot2_remote_control_frame.setGeometry(QtCore.QRect(10, 100, 231, 231))
        self.robot2_remote_control_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.robot2_remote_control_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.robot2_remote_control_frame.setObjectName("robot2_remote_control_frame")
        self.robot2_remote_control_label = QtWidgets.QLabel(self.robot2_remote_control_frame)
        self.robot2_remote_control_label.setGeometry(QtCore.QRect(10, 5, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.robot2_remote_control_label.setFont(font)
        self.robot2_remote_control_label.setObjectName("robot2_remote_control_label")
        
        ## controller
        self.button_center_robot2 = QtWidgets.QPushButton(self.robot2_remote_control_frame)
        self.button_center_robot2.setGeometry(QtCore.QRect(95,95,40,40))
        self.button_center_robot2.setObjectName("styleGroup6")

        
        icon_up = QtGui.QIcon()
        icon_up.addPixmap(QtGui.QPixmap(os.path.join(icons_dir,"arrow-up.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_up_robot2 = QtWidgets.QPushButton(self.robot2_remote_control_frame)
        self.button_up_robot2.setGeometry(QtCore.QRect(100,50,30,30))
        self.button_up_robot2.setIcon(icon_up)
        self.button_up_robot2.setObjectName("styleGroup1")
        self.button_up_robot2.setProperty("state","default")
        self.button_up_robot2.clicked.connect(lambda: self.toggleButtonStyle(self.button_up_robot2))
        
        icon_down = QtGui.QIcon()
        icon_down.addPixmap(QtGui.QPixmap(os.path.join(icons_dir,"arrow-down.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_down_robot2 = QtWidgets.QPushButton(self.robot2_remote_control_frame)
        self.button_down_robot2.setGeometry(QtCore.QRect(100,150,30,30))
        self.button_down_robot2.setIcon(icon_down)
        self.button_down_robot2.setObjectName("styleGroup1")
        self.button_down_robot2.setProperty("state","default")
        self.button_down_robot2.clicked.connect(lambda: self.toggleButtonStyle(self.button_down_robot2))

        
        icon_left = QtGui.QIcon()
        icon_left.addPixmap(QtGui.QPixmap(os.path.join(icons_dir,"arrow-left.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_left_robot2 = QtWidgets.QPushButton(self.robot2_remote_control_frame)
        self.button_left_robot2.setGeometry(QtCore.QRect(50,100,30,30))
        self.button_left_robot2.setIcon(icon_left)
        self.button_left_robot2.setObjectName("styleGroup1")
        self.button_left_robot2.setProperty("state","default")
        self.button_left_robot2.clicked.connect(lambda: self.toggleButtonStyle(self.button_left_robot2))

        
        icon_right = QtGui.QIcon()
        icon_right.addPixmap(QtGui.QPixmap(os.path.join(icons_dir,"arrow-right.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_right_robot2 = QtWidgets.QPushButton(self.robot2_remote_control_frame)
        self.button_right_robot2.setGeometry(QtCore.QRect(150,100,30,30))
        self.button_right_robot2.setIcon(icon_right)
        self.button_right_robot2.setObjectName("button_right_robot2")
        self.button_right_robot2.setObjectName("styleGroup1")
        self.button_right_robot2.setProperty("state","default")
        self.button_right_robot2.clicked.connect(lambda: self.toggleButtonStyle(self.button_right_robot2))

        
        icon_up_left = QtGui.QIcon()
        icon_up_left.addPixmap(QtGui.QPixmap(os.path.join(icons_dir,"arrow-up-left.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_up_left_robot2 = QtWidgets.QPushButton(self.robot2_remote_control_frame)
        self.button_up_left_robot2.setGeometry(QtCore.QRect(50,50,30,30))
        self.button_up_left_robot2.setIcon(icon_up_left)
        self.button_up_left_robot2.setObjectName("styleGroup1")
        self.button_up_left_robot2.setProperty("state","default")
        self.button_up_left_robot2.clicked.connect(lambda: self.toggleButtonStyle(self.button_up_left_robot2))

        
        icon_up_right = QtGui.QIcon()
        icon_up_right.addPixmap(QtGui.QPixmap(os.path.join(icons_dir,"arrow-up-right.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_up_right_robot2 = QtWidgets.QPushButton(self.robot2_remote_control_frame)
        self.button_up_right_robot2.setGeometry(QtCore.QRect(150,50,30,30))
        self.button_up_right_robot2.setIcon(icon_up_right)
        self.button_up_right_robot2.setObjectName("styleGroup1")
        self.button_up_right_robot2.setProperty("state","default")
        self.button_up_right_robot2.clicked.connect(lambda: self.toggleButtonStyle(self.button_up_right_robot2))

        
        icon_down_left = QtGui.QIcon()
        icon_down_left.addPixmap(QtGui.QPixmap(os.path.join(icons_dir,"arrow-down-left.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_down_left_robot2 = QtWidgets.QPushButton(self.robot2_remote_control_frame)
        self.button_down_left_robot2.setGeometry(QtCore.QRect(50,150,30,30))
        self.button_down_left_robot2.setIcon(icon_down_left)
        self.button_down_left_robot2.setObjectName("styleGroup1")
        self.button_down_left_robot2.setProperty("state","default")
        self.button_down_left_robot2.clicked.connect(lambda: self.toggleButtonStyle(self.button_down_left_robot2))

        
        icon_down_right = QtGui.QIcon()
        icon_down_right.addPixmap(QtGui.QPixmap(os.path.join(icons_dir,"arrow-down-right.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_down_right_robot2 = QtWidgets.QPushButton(self.robot2_remote_control_frame)
        self.button_down_right_robot2.setGeometry(QtCore.QRect(150,150,30,30))
        self.button_down_right_robot2.setIcon(icon_down_right)
        self.button_down_right_robot2.setObjectName("styleGroup1")
        self.button_down_right_robot2.setProperty("state","default")        
        self.button_down_right_robot2.clicked.connect(lambda: self.toggleButtonStyle(self.button_down_right_robot2))

        
        
        # remote control frame part 2
        self.robot2_wheel_leg_control_frame = QtWidgets.QFrame(self.control_mode_remote_large_frame)
        self.robot2_wheel_leg_control_frame.setGeometry(QtCore.QRect(250, 100, 231, 231))
        self.robot2_wheel_leg_control_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.robot2_wheel_leg_control_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.robot2_wheel_leg_control_frame.setObjectName("robot2_wheel_leg_control_frame")
        self.robot2_wheel_leg_control_label = QtWidgets.QLabel(self.robot2_wheel_leg_control_frame)
        self.robot2_wheel_leg_control_label.setGeometry(QtCore.QRect(10, 5, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.robot2_wheel_leg_control_label.setFont(font)
        self.robot2_wheel_leg_control_label.setObjectName("robot2_wheel_leg_control_label")
        
        
        
        ## controller
        self.button_center_robot1 = QtWidgets.QPushButton(self.robot2_wheel_leg_control_frame)
        self.button_center_robot1.setGeometry(QtCore.QRect(95,95,40,40))
        self.button_center_robot1.setObjectName("styleGroup6")

        

        self.button_up_robot1 = QtWidgets.QPushButton(self.robot2_wheel_leg_control_frame)
        self.button_up_robot1.setGeometry(QtCore.QRect(100,50,30,30))
        self.button_up_robot1.setIcon(icon_up)
        self.button_up_robot1.setObjectName("styleGroup1")
        self.button_up_robot1.setProperty("state","default")
        self.button_up_robot1.clicked.connect(lambda: self.toggleButtonStyle(self.button_up_robot1))
        

        self.button_down_robot1 = QtWidgets.QPushButton(self.robot2_wheel_leg_control_frame)
        self.button_down_robot1.setGeometry(QtCore.QRect(100,150,30,30))
        self.button_down_robot1.setIcon(icon_down)
        self.button_down_robot1.setObjectName("styleGroup1")
        self.button_down_robot1.setProperty("state","default")
        self.button_down_robot1.clicked.connect(lambda: self.toggleButtonStyle(self.button_down_robot1))


        self.button_left_robot1 = QtWidgets.QPushButton(self.robot2_wheel_leg_control_frame)
        self.button_left_robot1.setGeometry(QtCore.QRect(50,100,30,30))
        self.button_left_robot1.setIcon(icon_left)
        self.button_left_robot1.setObjectName("styleGroup1")
        self.button_left_robot1.setProperty("state","default")
        self.button_left_robot1.clicked.connect(lambda: self.toggleButtonStyle(self.button_left_robot1))


        self.button_right_robot1 = QtWidgets.QPushButton(self.robot2_wheel_leg_control_frame)
        self.button_right_robot1.setGeometry(QtCore.QRect(150,100,30,30))
        self.button_right_robot1.setIcon(icon_right)
        self.button_right_robot1.setObjectName("button_right_robot1")
        self.button_right_robot1.setObjectName("styleGroup1")
        self.button_right_robot1.setProperty("state","default")
        self.button_right_robot1.clicked.connect(lambda: self.toggleButtonStyle(self.button_right_robot1))


        self.button_up_left_robot1 = QtWidgets.QPushButton(self.robot2_wheel_leg_control_frame)
        self.button_up_left_robot1.setGeometry(QtCore.QRect(50,50,30,30))
        self.button_up_left_robot1.setIcon(icon_up_left)
        self.button_up_left_robot1.setObjectName("styleGroup1")
        self.button_up_left_robot1.setProperty("state","default")
        self.button_up_left_robot1.clicked.connect(lambda: self.toggleButtonStyle(self.button_up_left_robot1))


        self.button_up_right_robot1 = QtWidgets.QPushButton(self.robot2_wheel_leg_control_frame)
        self.button_up_right_robot1.setGeometry(QtCore.QRect(150,50,30,30))
        self.button_up_right_robot1.setIcon(icon_up_right)
        self.button_up_right_robot1.setObjectName("styleGroup1")
        self.button_up_right_robot1.setProperty("state","default")
        self.button_up_right_robot1.clicked.connect(lambda: self.toggleButtonStyle(self.button_up_right_robot1))


        self.button_down_left_robot1 = QtWidgets.QPushButton(self.robot2_wheel_leg_control_frame)
        self.button_down_left_robot1.setGeometry(QtCore.QRect(50,150,30,30))
        self.button_down_left_robot1.setIcon(icon_down_left)
        self.button_down_left_robot1.setObjectName("styleGroup1")
        self.button_down_left_robot1.setProperty("state","default")
        self.button_down_left_robot1.clicked.connect(lambda: self.toggleButtonStyle(self.button_down_left_robot1))


        self.button_down_right_robot1 = QtWidgets.QPushButton(self.robot2_wheel_leg_control_frame)
        self.button_down_right_robot1.setGeometry(QtCore.QRect(150,150,30,30))
        self.button_down_right_robot1.setIcon(icon_down_right)
        self.button_down_right_robot1.setObjectName("styleGroup1")
        self.button_down_right_robot1.setProperty("state","default")        
        self.button_down_right_robot1.clicked.connect(lambda: self.toggleButtonStyle(self.button_down_right_robot1))
        
        
        self.joint_control_large_frame = QtWidgets.QFrame(self.centralwidget)
        self.joint_control_large_frame.setGeometry(QtCore.QRect(735, 50, 431, 341))
        self.joint_control_large_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joint_control_large_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joint_control_large_frame.setObjectName("joint_control_large_frame")
        self.joint_control_FL_frame = QtWidgets.QFrame(self.joint_control_large_frame)
        self.joint_control_FL_frame.setGeometry(QtCore.QRect(9, 28, 416, 75))
        self.joint_control_FL_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joint_control_FL_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joint_control_FL_frame.setObjectName("joint_control_FL_frame")
        self.joint_control_FL_label = QtWidgets.QLabel(self.joint_control_FL_frame)
        self.joint_control_FL_label.setGeometry(QtCore.QRect(7, 30, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.joint_control_FL_label.setFont(font)
        self.joint_control_FL_label.setObjectName("joint_control_FL_label")
        self.joint_control_FL_x_frame = QtWidgets.QFrame(self.joint_control_FL_frame)
        self.joint_control_FL_x_frame.setGeometry(QtCore.QRect(30, 2, 125, 71))
        self.joint_control_FL_x_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joint_control_FL_x_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joint_control_FL_x_frame.setObjectName("joint_control_FL_x_frame")
        self.joint_control_FL_x_textedit = QtWidgets.QTextEdit(self.joint_control_FL_x_frame)
        self.joint_control_FL_x_textedit.setGeometry(QtCore.QRect(7, 7, 45, 25))
        self.joint_control_FL_x_textedit.setObjectName("joint_control_FL_x_textedit")
        self.joint_control_FL_x_display = QtWidgets.QTextBrowser(self.joint_control_FL_x_frame)
        self.joint_control_FL_x_display.setGeometry(QtCore.QRect(7, 37, 80, 25))
        self.joint_control_FL_x_display.setObjectName("joint_control_FL_x_display")
        
        self.joint_control_FL_x_plus_button = QtWidgets.QPushButton(self.joint_control_FL_x_frame)
        self.joint_control_FL_x_plus_button.setGeometry(QtCore.QRect(90, 7, 31, 25))
        self.joint_control_FL_x_plus_button.setText("")
        self.joint_control_FL_x_plus_button.setObjectName("styleGroup4")
        
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(os.path.join(icons_dir,"plus.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.joint_control_FL_x_plus_button.setIcon(icon4)
        self.joint_control_FL_x_plus_button.setObjectName("joint_control_FL_x_plus_button")
        self.joint_control_FL_x_plus_button.setObjectName("styleGroup4")
        self.joint_control_FL_x_minus_button = QtWidgets.QPushButton(self.joint_control_FL_x_frame)
        self.joint_control_FL_x_minus_button.setGeometry(QtCore.QRect(90, 37, 31, 25))
        self.joint_control_FL_x_minus_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(os.path.join(icons_dir,"minus.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.joint_control_FL_x_minus_button.setIcon(icon5)
        self.joint_control_FL_x_minus_button.setObjectName("joint_control_FL_x_minus_button")
        self.joint_control_FL_x_minus_button.setObjectName("styleGroup4")
        
        self.joint_control_FL_x_set_button = QtWidgets.QPushButton(self.joint_control_FL_x_frame)
        self.joint_control_FL_x_set_button.setGeometry(QtCore.QRect(56, 7, 31, 25))
        self.joint_control_FL_x_set_button.setObjectName("joint_control_FL_x_set_button")
        self.joint_control_FL_x_set_button.setObjectName("styleGroup5")
        
        self.joint_control_FL_y_frame = QtWidgets.QFrame(self.joint_control_FL_frame)
        self.joint_control_FL_y_frame.setGeometry(QtCore.QRect(158, 2, 125, 71))
        self.joint_control_FL_y_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joint_control_FL_y_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joint_control_FL_y_frame.setObjectName("joint_control_FL_y_frame")
        self.joint_control_FL_y_textedit = QtWidgets.QTextEdit(self.joint_control_FL_y_frame)
        self.joint_control_FL_y_textedit.setGeometry(QtCore.QRect(7, 7, 45, 25))
        self.joint_control_FL_y_textedit.setObjectName("joint_control_FL_y_textedit")
        self.joint_control_FL_y_display = QtWidgets.QTextBrowser(self.joint_control_FL_y_frame)
        self.joint_control_FL_y_display.setGeometry(QtCore.QRect(7, 37, 80, 25))
        self.joint_control_FL_y_display.setObjectName("joint_control_FL_y_display")
        
        self.joint_control_FL_y_plus_button = QtWidgets.QPushButton(self.joint_control_FL_y_frame)
        self.joint_control_FL_y_plus_button.setGeometry(QtCore.QRect(90, 7, 31, 25))
        self.joint_control_FL_y_plus_button.setText("")
        self.joint_control_FL_y_plus_button.setIcon(icon4)
        self.joint_control_FL_y_plus_button.setObjectName("joint_control_FL_y_plus_button")
        self.joint_control_FL_y_plus_button.setObjectName("styleGroup4")
        
        self.joint_control_FL_y_minus_button = QtWidgets.QPushButton(self.joint_control_FL_y_frame)
        self.joint_control_FL_y_minus_button.setGeometry(QtCore.QRect(90, 37, 31, 25))
        self.joint_control_FL_y_minus_button.setText("")
        self.joint_control_FL_y_minus_button.setIcon(icon5)
        self.joint_control_FL_y_minus_button.setObjectName("joint_control_FL_y_minus_button")
        self.joint_control_FL_y_minus_button.setObjectName("styleGroup4")
        
        self.joint_control_FL_y_set_button = QtWidgets.QPushButton(self.joint_control_FL_y_frame)
        self.joint_control_FL_y_set_button.setGeometry(QtCore.QRect(56, 7, 31, 25))
        self.joint_control_FL_y_set_button.setObjectName("joint_control_FL_y_set_button")
        self.joint_control_FL_y_set_button.setObjectName("styleGroup5")
        
        self.joint_control_FL_z_frame = QtWidgets.QFrame(self.joint_control_FL_frame)
        self.joint_control_FL_z_frame.setGeometry(QtCore.QRect(286, 2, 125, 71))
        self.joint_control_FL_z_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joint_control_FL_z_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joint_control_FL_z_frame.setObjectName("joint_control_FL_z_frame")
        self.joint_control_FL_z_textedit = QtWidgets.QTextEdit(self.joint_control_FL_z_frame)
        self.joint_control_FL_z_textedit.setGeometry(QtCore.QRect(7, 7, 45, 25))
        self.joint_control_FL_z_textedit.setObjectName("joint_control_FL_z_textedit")
        self.joint_control_FL_z_display = QtWidgets.QTextBrowser(self.joint_control_FL_z_frame)
        self.joint_control_FL_z_display.setGeometry(QtCore.QRect(7, 37, 80, 25))
        self.joint_control_FL_z_display.setObjectName("joint_control_FL_z_display")
        
        self.joint_control_FL_z_plus_button = QtWidgets.QPushButton(self.joint_control_FL_z_frame)
        self.joint_control_FL_z_plus_button.setGeometry(QtCore.QRect(90, 7, 31, 25))
        self.joint_control_FL_z_plus_button.setText("")
        self.joint_control_FL_z_plus_button.setIcon(icon4)
        self.joint_control_FL_z_plus_button.setObjectName("joint_control_FL_z_plus_button")
        self.joint_control_FL_z_plus_button.setObjectName("styleGroup4")
        
        self.joint_control_FL_z_minus_button = QtWidgets.QPushButton(self.joint_control_FL_z_frame)
        self.joint_control_FL_z_minus_button.setGeometry(QtCore.QRect(90, 37, 31, 25))
        self.joint_control_FL_z_minus_button.setText("")
        self.joint_control_FL_z_minus_button.setIcon(icon5)
        self.joint_control_FL_z_minus_button.setObjectName("joint_control_FL_z_minus_button")
        self.joint_control_FL_z_minus_button.setObjectName("styleGroup4")
        
        self.joint_control_FL_z_set_button = QtWidgets.QPushButton(self.joint_control_FL_z_frame)
        self.joint_control_FL_z_set_button.setGeometry(QtCore.QRect(56, 7, 31, 25))
        self.joint_control_FL_z_set_button.setObjectName("joint_control_FL_z_set_button")
        self.joint_control_FL_z_set_button.setObjectName("styleGroup5")
        
        self.joint_control_FR_frame = QtWidgets.QFrame(self.joint_control_large_frame)
        self.joint_control_FR_frame.setGeometry(QtCore.QRect(9, 104, 417, 75))
        self.joint_control_FR_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joint_control_FR_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joint_control_FR_frame.setObjectName("joint_control_FR_frame")
        self.joint_control_FR_labal = QtWidgets.QLabel(self.joint_control_FR_frame)
        self.joint_control_FR_labal.setGeometry(QtCore.QRect(7, 30, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.joint_control_FR_labal.setFont(font)
        self.joint_control_FR_labal.setObjectName("joint_control_FR_labal")
        
        self.joint_control_FR_z_frame = QtWidgets.QFrame(self.joint_control_FR_frame)
        self.joint_control_FR_z_frame.setGeometry(QtCore.QRect(286, 2, 125, 71))
        self.joint_control_FR_z_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joint_control_FR_z_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joint_control_FR_z_frame.setObjectName("joint_control_FR_z_frame")
        self.joint_control_FR_z_textedit = QtWidgets.QTextEdit(self.joint_control_FR_z_frame)
        self.joint_control_FR_z_textedit.setGeometry(QtCore.QRect(7, 7, 45, 25))
        self.joint_control_FR_z_textedit.setObjectName("joint_control_FR_z_textedit")
        self.joint_control_FR_z_display = QtWidgets.QTextBrowser(self.joint_control_FR_z_frame)
        self.joint_control_FR_z_display.setGeometry(QtCore.QRect(7, 37, 80, 25))
        self.joint_control_FR_z_display.setObjectName("joint_control_FR_z_display")
        
        self.joint_control_FR_z_plus_button = QtWidgets.QPushButton(self.joint_control_FR_z_frame)
        self.joint_control_FR_z_plus_button.setGeometry(QtCore.QRect(90, 7, 31, 25))
        self.joint_control_FR_z_plus_button.setText("")
        self.joint_control_FR_z_plus_button.setIcon(icon4)
        self.joint_control_FR_z_plus_button.setObjectName("joint_control_FR_z_plus_button")
        self.joint_control_FR_z_plus_button.setObjectName("styleGroup4")
        
        self.joint_control_FR_z_minus_button = QtWidgets.QPushButton(self.joint_control_FR_z_frame)
        self.joint_control_FR_z_minus_button.setGeometry(QtCore.QRect(90, 37, 31, 25))
        self.joint_control_FR_z_minus_button.setText("")
        self.joint_control_FR_z_minus_button.setIcon(icon5)
        self.joint_control_FR_z_minus_button.setObjectName("joint_control_FR_z_minus_button")
        self.joint_control_FR_z_minus_button.setObjectName("styleGroup4")
        
        self.joint_control_FR_z_set_button = QtWidgets.QPushButton(self.joint_control_FR_z_frame)
        self.joint_control_FR_z_set_button.setGeometry(QtCore.QRect(56, 7, 31, 25))
        self.joint_control_FR_z_set_button.setObjectName("joint_control_FR_z_set_button")
        self.joint_control_FR_z_set_button.setObjectName("styleGroup5")
        
        self.joint_control_FR_x_frame = QtWidgets.QFrame(self.joint_control_FR_frame)
        self.joint_control_FR_x_frame.setGeometry(QtCore.QRect(30, 2, 125, 71))
        self.joint_control_FR_x_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joint_control_FR_x_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joint_control_FR_x_frame.setObjectName("joint_control_FR_x_frame")
        self.joint_control_FR_x_textedit = QtWidgets.QTextEdit(self.joint_control_FR_x_frame)
        self.joint_control_FR_x_textedit.setGeometry(QtCore.QRect(7, 7, 45, 25))
        self.joint_control_FR_x_textedit.setObjectName("joint_control_FR_x_textedit")
        self.joint_control_FR_x_display = QtWidgets.QTextBrowser(self.joint_control_FR_x_frame)
        self.joint_control_FR_x_display.setGeometry(QtCore.QRect(7, 37, 80, 25))
        self.joint_control_FR_x_display.setObjectName("joint_control_FR_x_display")
        
        
        self.joint_control_FR_x_plus_button = QtWidgets.QPushButton(self.joint_control_FR_x_frame)
        self.joint_control_FR_x_plus_button.setGeometry(QtCore.QRect(90, 7, 31, 25))
        self.joint_control_FR_x_plus_button.setText("")
        self.joint_control_FR_x_plus_button.setIcon(icon4)
        self.joint_control_FR_x_plus_button.setObjectName("joint_control_FR_x_plus_button")
        self.joint_control_FR_x_plus_button.setObjectName("styleGroup4")
        
        self.joint_control_FR_x_minus_button = QtWidgets.QPushButton(self.joint_control_FR_x_frame)
        self.joint_control_FR_x_minus_button.setGeometry(QtCore.QRect(90, 37, 31, 25))
        self.joint_control_FR_x_minus_button.setText("")
        self.joint_control_FR_x_minus_button.setIcon(icon5)
        self.joint_control_FR_x_minus_button.setObjectName("joint_control_FR_x_minus_button")
        self.joint_control_FR_x_minus_button.setObjectName("styleGroup4")
        
        self.joint_control_FR_x_set_button = QtWidgets.QPushButton(self.joint_control_FR_x_frame)
        self.joint_control_FR_x_set_button.setGeometry(QtCore.QRect(56, 7, 31, 25))
        self.joint_control_FR_x_set_button.setObjectName("joint_control_FR_x_set_button")
        self.joint_control_FR_x_set_button.setObjectName("styleGroup5")
        
        self.joint_control_FR_y_frame = QtWidgets.QFrame(self.joint_control_FR_frame)
        self.joint_control_FR_y_frame.setGeometry(QtCore.QRect(158, 2, 125, 71))
        self.joint_control_FR_y_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joint_control_FR_y_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joint_control_FR_y_frame.setObjectName("joint_control_FR_y_frame")
        self.joint_control_FR_y_textedit = QtWidgets.QTextEdit(self.joint_control_FR_y_frame)
        self.joint_control_FR_y_textedit.setGeometry(QtCore.QRect(7, 7, 45, 25))
        self.joint_control_FR_y_textedit.setObjectName("joint_control_FR_y_textedit")
        self.joint_control_FR_y_display = QtWidgets.QTextBrowser(self.joint_control_FR_y_frame)
        self.joint_control_FR_y_display.setGeometry(QtCore.QRect(7, 37, 80, 25))
        self.joint_control_FR_y_display.setObjectName("joint_control_FR_y_display")
        
        self.joint_control_FR_y_plus_button = QtWidgets.QPushButton(self.joint_control_FR_y_frame)
        self.joint_control_FR_y_plus_button.setGeometry(QtCore.QRect(90, 7, 31, 25))
        self.joint_control_FR_y_plus_button.setText("")
        self.joint_control_FR_y_plus_button.setIcon(icon4)
        self.joint_control_FR_y_plus_button.setObjectName("joint_control_FR_y_plus_button")
        self.joint_control_FR_y_plus_button.setObjectName("styleGroup4")
        
        self.joint_control_FR_y_minus_button = QtWidgets.QPushButton(self.joint_control_FR_y_frame)
        self.joint_control_FR_y_minus_button.setGeometry(QtCore.QRect(90, 37, 31, 25))
        self.joint_control_FR_y_minus_button.setText("")
        self.joint_control_FR_y_minus_button.setIcon(icon5)
        self.joint_control_FR_y_minus_button.setObjectName("joint_control_FR_y_minus_button")
        self.joint_control_FR_y_minus_button.setObjectName("styleGroup4")
        
        self.joint_control_FR_y_set_button = QtWidgets.QPushButton(self.joint_control_FR_y_frame)
        self.joint_control_FR_y_set_button.setGeometry(QtCore.QRect(56, 7, 31, 25))
        self.joint_control_FR_y_set_button.setObjectName("joint_control_FR_y_set_button")
        self.joint_control_FR_y_set_button.setObjectName("styleGroup5")
        
        self.joint_control_RL_frame = QtWidgets.QFrame(self.joint_control_large_frame)
        self.joint_control_RL_frame.setGeometry(QtCore.QRect(9, 180, 417, 75))
        self.joint_control_RL_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joint_control_RL_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joint_control_RL_frame.setObjectName("joint_control_RL_frame")
        self.joint_control_RL_label = QtWidgets.QLabel(self.joint_control_RL_frame)
        self.joint_control_RL_label.setGeometry(QtCore.QRect(7, 30, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.joint_control_RL_label.setFont(font)
        self.joint_control_RL_label.setObjectName("joint_control_RL_label")
        self.joint_control_RL_z_frame = QtWidgets.QFrame(self.joint_control_RL_frame)
        self.joint_control_RL_z_frame.setGeometry(QtCore.QRect(286, 2, 125, 71))
        self.joint_control_RL_z_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joint_control_RL_z_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joint_control_RL_z_frame.setObjectName("joint_control_RL_z_frame")
        self.joint_control_RL_z_textedit = QtWidgets.QTextEdit(self.joint_control_RL_z_frame)
        self.joint_control_RL_z_textedit.setGeometry(QtCore.QRect(7, 7, 45, 25))
        self.joint_control_RL_z_textedit.setObjectName("joint_control_RL_z_textedit")
        self.joint_control_RL_z_display = QtWidgets.QTextBrowser(self.joint_control_RL_z_frame)
        self.joint_control_RL_z_display.setGeometry(QtCore.QRect(7, 37, 80, 25))
        self.joint_control_RL_z_display.setObjectName("joint_control_RL_z_display")
        
        self.joint_control_RL_z_plus_button = QtWidgets.QPushButton(self.joint_control_RL_z_frame)
        self.joint_control_RL_z_plus_button.setGeometry(QtCore.QRect(90, 7, 31, 25))
        self.joint_control_RL_z_plus_button.setText("")
        self.joint_control_RL_z_plus_button.setIcon(icon4)
        self.joint_control_RL_z_plus_button.setObjectName("joint_control_RL_z_plus_button")
        self.joint_control_RL_z_plus_button.setObjectName("styleGroup4")
        
        self.joint_control_RL_z_minus_button = QtWidgets.QPushButton(self.joint_control_RL_z_frame)
        self.joint_control_RL_z_minus_button.setGeometry(QtCore.QRect(90, 37, 31, 25))
        self.joint_control_RL_z_minus_button.setText("")
        self.joint_control_RL_z_minus_button.setIcon(icon5)
        self.joint_control_RL_z_minus_button.setObjectName("joint_control_RL_z_minus_button")
        self.joint_control_RL_z_minus_button.setObjectName("styleGroup4")
        
        self.joint_control_RL_z_set_button = QtWidgets.QPushButton(self.joint_control_RL_z_frame)
        self.joint_control_RL_z_set_button.setGeometry(QtCore.QRect(56, 7, 31, 25))
        self.joint_control_RL_z_set_button.setObjectName("joint_control_RL_z_set_button")
        self.joint_control_RL_z_set_button.setObjectName("styleGroup5")
        
        self.joint_control_RL_x_frame = QtWidgets.QFrame(self.joint_control_RL_frame)
        self.joint_control_RL_x_frame.setGeometry(QtCore.QRect(30, 2, 125, 71))
        self.joint_control_RL_x_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joint_control_RL_x_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joint_control_RL_x_frame.setObjectName("joint_control_RL_x_frame")
        self.joint_control_RL_x_textedit = QtWidgets.QTextEdit(self.joint_control_RL_x_frame)
        self.joint_control_RL_x_textedit.setGeometry(QtCore.QRect(7, 7, 45, 25))
        self.joint_control_RL_x_textedit.setObjectName("joint_control_RL_x_textedit")
        self.joint_control_RL_x_display = QtWidgets.QTextBrowser(self.joint_control_RL_x_frame)
        self.joint_control_RL_x_display.setGeometry(QtCore.QRect(7, 37, 80, 25))
        self.joint_control_RL_x_display.setObjectName("joint_control_RL_x_display")
        
        self.joint_control_RL_x_plus_button = QtWidgets.QPushButton(self.joint_control_RL_x_frame)
        self.joint_control_RL_x_plus_button.setGeometry(QtCore.QRect(90, 7, 31, 25))
        self.joint_control_RL_x_plus_button.setText("")
        self.joint_control_RL_x_plus_button.setIcon(icon4)
        self.joint_control_RL_x_plus_button.setObjectName("joint_control_RL_x_plus_button")
        self.joint_control_RL_x_plus_button.setObjectName("styleGroup4")
        
        self.joint_control_RL_x_minus_button = QtWidgets.QPushButton(self.joint_control_RL_x_frame)
        self.joint_control_RL_x_minus_button.setGeometry(QtCore.QRect(90, 37, 31, 25))
        self.joint_control_RL_x_minus_button.setText("")
        self.joint_control_RL_x_minus_button.setIcon(icon5)
        self.joint_control_RL_x_minus_button.setObjectName("joint_control_RL_x_minus_button")
        self.joint_control_RL_x_minus_button.setObjectName("styleGroup4")
        
        self.joint_control_RL_x_set_button = QtWidgets.QPushButton(self.joint_control_RL_x_frame)
        self.joint_control_RL_x_set_button.setGeometry(QtCore.QRect(56, 7, 31, 25))
        self.joint_control_RL_x_set_button.setObjectName("joint_control_RL_x_set_button")
        self.joint_control_RL_x_set_button.setObjectName("styleGroup5")
        
        self.joint_control_RL_y_frame = QtWidgets.QFrame(self.joint_control_RL_frame)
        self.joint_control_RL_y_frame.setGeometry(QtCore.QRect(158, 2, 125, 71))
        self.joint_control_RL_y_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joint_control_RL_y_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joint_control_RL_y_frame.setObjectName("joint_control_RL_y_frame")
        self.joint_control_RL_y_textedit = QtWidgets.QTextEdit(self.joint_control_RL_y_frame)
        self.joint_control_RL_y_textedit.setGeometry(QtCore.QRect(7, 7, 45, 25))
        self.joint_control_RL_y_textedit.setObjectName("joint_control_RL_y_textedit")
        self.joint_control_RL_y_display = QtWidgets.QTextBrowser(self.joint_control_RL_y_frame)
        self.joint_control_RL_y_display.setGeometry(QtCore.QRect(7, 37, 80, 25))
        self.joint_control_RL_y_display.setObjectName("joint_control_RL_y_display")
        
        
        self.joint_control_RL_y_plus_button = QtWidgets.QPushButton(self.joint_control_RL_y_frame)
        self.joint_control_RL_y_plus_button.setGeometry(QtCore.QRect(90, 7, 31, 25))
        self.joint_control_RL_y_plus_button.setText("")
        self.joint_control_RL_y_plus_button.setIcon(icon4)
        self.joint_control_RL_y_plus_button.setObjectName("joint_control_RL_y_plus_button")
        self.joint_control_RL_y_plus_button.setObjectName("styleGroup4")
        
        self.joint_control_RL_y_minus_button = QtWidgets.QPushButton(self.joint_control_RL_y_frame)
        self.joint_control_RL_y_minus_button.setGeometry(QtCore.QRect(90, 37, 31, 25))
        self.joint_control_RL_y_minus_button.setText("")
        self.joint_control_RL_y_minus_button.setIcon(icon5)
        self.joint_control_RL_y_minus_button.setObjectName("joint_control_RL_y_minus_button")
        self.joint_control_RL_y_minus_button.setObjectName("styleGroup4")
        
        self.joint_control_RL_y_set_button = QtWidgets.QPushButton(self.joint_control_RL_y_frame)
        self.joint_control_RL_y_set_button.setGeometry(QtCore.QRect(56, 7, 31, 25))
        self.joint_control_RL_y_set_button.setObjectName("joint_control_RL_y_set_button")
        self.joint_control_RL_y_set_button.setObjectName("styleGroup5")
        
        self.joint_control_RR_frame = QtWidgets.QFrame(self.joint_control_large_frame)
        self.joint_control_RR_frame.setGeometry(QtCore.QRect(9, 256, 417, 75))
        self.joint_control_RR_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joint_control_RR_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joint_control_RR_frame.setObjectName("joint_control_RR_frame")
        self.joint_control_RR_label = QtWidgets.QLabel(self.joint_control_RR_frame)
        self.joint_control_RR_label.setGeometry(QtCore.QRect(7, 30, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        
        self.joint_control_RR_label.setFont(font)
        self.joint_control_RR_label.setObjectName("joint_control_RR_label")
        self.joint_control_RR_z_frame = QtWidgets.QFrame(self.joint_control_RR_frame)
        self.joint_control_RR_z_frame.setGeometry(QtCore.QRect(286, 2, 125, 71))
        self.joint_control_RR_z_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joint_control_RR_z_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joint_control_RR_z_frame.setObjectName("joint_control_RR_z_frame")
        self.joint_control_RR_z_textedit = QtWidgets.QTextEdit(self.joint_control_RR_z_frame)
        self.joint_control_RR_z_textedit.setGeometry(QtCore.QRect(7, 7, 45, 25))
        self.joint_control_RR_z_textedit.setObjectName("joint_control_RR_z_textedit")
        self.joint_control_RR_z_display = QtWidgets.QTextBrowser(self.joint_control_RR_z_frame)
        self.joint_control_RR_z_display.setGeometry(QtCore.QRect(7, 37, 80, 25))
        self.joint_control_RR_z_display.setObjectName("joint_control_RR_z_display")
        
        self.joint_control_RR_z_plus_button = QtWidgets.QPushButton(self.joint_control_RR_z_frame)
        self.joint_control_RR_z_plus_button.setGeometry(QtCore.QRect(90, 7, 31, 25))
        self.joint_control_RR_z_plus_button.setText("")
        self.joint_control_RR_z_plus_button.setIcon(icon4)
        self.joint_control_RR_z_plus_button.setObjectName("joint_control_RR_z_plus_button")
        self.joint_control_RR_z_plus_button.setObjectName("styleGroup4")
        
        self.joint_control_RR_z_minus_button = QtWidgets.QPushButton(self.joint_control_RR_z_frame)
        self.joint_control_RR_z_minus_button.setGeometry(QtCore.QRect(90, 37, 31, 25))
        self.joint_control_RR_z_minus_button.setText("")
        self.joint_control_RR_z_minus_button.setIcon(icon5)
        self.joint_control_RR_z_minus_button.setObjectName("joint_control_RR_z_minus_button")
        self.joint_control_RR_z_minus_button.setObjectName("styleGroup4")
        
        self.joint_control_RR_z_set_button = QtWidgets.QPushButton(self.joint_control_RR_z_frame)
        self.joint_control_RR_z_set_button.setGeometry(QtCore.QRect(56, 7, 31, 25))
        self.joint_control_RR_z_set_button.setObjectName("joint_control_RR_z_set_button")
        self.joint_control_RR_z_set_button.setObjectName("styleGroup5")
        
        self.joint_control_RR_x_frame = QtWidgets.QFrame(self.joint_control_RR_frame)
        self.joint_control_RR_x_frame.setGeometry(QtCore.QRect(30, 2, 125, 71))
        self.joint_control_RR_x_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joint_control_RR_x_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joint_control_RR_x_frame.setObjectName("joint_control_RR_x_frame")
        self.joint_control_RR_x_textedit = QtWidgets.QTextEdit(self.joint_control_RR_x_frame)
        self.joint_control_RR_x_textedit.setGeometry(QtCore.QRect(7, 7, 45, 25))
        self.joint_control_RR_x_textedit.setObjectName("joint_control_RR_x_textedit")
        self.joint_control_RR_x_display = QtWidgets.QTextBrowser(self.joint_control_RR_x_frame)
        self.joint_control_RR_x_display.setGeometry(QtCore.QRect(7, 37, 80, 25))
        self.joint_control_RR_x_display.setObjectName("joint_control_RR_x_display")
        
        self.joint_control_RR_x_plus_button = QtWidgets.QPushButton(self.joint_control_RR_x_frame)
        self.joint_control_RR_x_plus_button.setGeometry(QtCore.QRect(90, 7, 31, 25))
        self.joint_control_RR_x_plus_button.setText("")
        self.joint_control_RR_x_plus_button.setIcon(icon4)
        self.joint_control_RR_x_plus_button.setObjectName("joint_control_RR_x_plus_button")
        self.joint_control_RR_x_plus_button.setObjectName("styleGroup4")
        
        self.joint_control_RR_x_minus_button = QtWidgets.QPushButton(self.joint_control_RR_x_frame)
        self.joint_control_RR_x_minus_button.setGeometry(QtCore.QRect(90, 37, 31, 25))
        self.joint_control_RR_x_minus_button.setText("")
        self.joint_control_RR_x_minus_button.setIcon(icon5)
        self.joint_control_RR_x_minus_button.setObjectName("joint_control_RR_x_minus_button")
        self.joint_control_RR_x_minus_button.setObjectName("styleGroup4")
        
        self.joint_control_RR_x_set_button = QtWidgets.QPushButton(self.joint_control_RR_x_frame)
        self.joint_control_RR_x_set_button.setGeometry(QtCore.QRect(56, 7, 31, 25))
        self.joint_control_RR_x_set_button.setObjectName("joint_control_RR_x_set_button")
        self.joint_control_RR_x_set_button.setObjectName("styleGroup5")
        
        self.joint_control_RR_y_frame = QtWidgets.QFrame(self.joint_control_RR_frame)
        self.joint_control_RR_y_frame.setGeometry(QtCore.QRect(158, 2, 125, 71))
        self.joint_control_RR_y_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joint_control_RR_y_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joint_control_RR_y_frame.setObjectName("joint_control_RR_y_frame")
        self.joint_control_RR_y_textedit = QtWidgets.QTextEdit(self.joint_control_RR_y_frame)
        self.joint_control_RR_y_textedit.setGeometry(QtCore.QRect(7, 7, 45, 25))
        self.joint_control_RR_y_textedit.setObjectName("joint_control_RR_y_textedit")
        self.joint_control_RR_y_display = QtWidgets.QTextBrowser(self.joint_control_RR_y_frame)
        self.joint_control_RR_y_display.setGeometry(QtCore.QRect(7, 37, 80, 25))
        self.joint_control_RR_y_display.setObjectName("joint_control_RR_y_display")
        
        self.joint_control_RR_y_plus_button = QtWidgets.QPushButton(self.joint_control_RR_y_frame)
        self.joint_control_RR_y_plus_button.setGeometry(QtCore.QRect(90, 7, 31, 25))
        self.joint_control_RR_y_plus_button.setText("")
        self.joint_control_RR_y_plus_button.setIcon(icon4)
        self.joint_control_RR_y_plus_button.setObjectName("joint_control_RR_y_plus_button")
        self.joint_control_RR_y_plus_button.setObjectName("styleGroup4")
        
        self.joint_control_RR_y_minus_button = QtWidgets.QPushButton(self.joint_control_RR_y_frame)
        self.joint_control_RR_y_minus_button.setGeometry(QtCore.QRect(90, 37, 31, 25))
        self.joint_control_RR_y_minus_button.setText("")
        self.joint_control_RR_y_minus_button.setIcon(icon5)
        self.joint_control_RR_y_minus_button.setObjectName("joint_control_RR_y_minus_button")
        self.joint_control_RR_y_minus_button.setObjectName("styleGroup4")
        
        self.joint_control_RR_y_set_button = QtWidgets.QPushButton(self.joint_control_RR_y_frame)
        self.joint_control_RR_y_set_button.setGeometry(QtCore.QRect(56, 7, 31, 25))
        self.joint_control_RR_y_set_button.setObjectName("joint_control_RR_y_set_button")
        self.joint_control_RR_y_set_button.setObjectName("styleGroup5")
        
        
        icon_chev_up = QtGui.QIcon()
        icon_chev_up.addPixmap(QtGui.QPixmap(os.path.join(icons_dir,"chevrons-up.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        
        icon_chev_down = QtGui.QIcon()
        icon_chev_down.addPixmap(QtGui.QPixmap(os.path.join(icons_dir,"chevrons-down.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        
        icon_chev_stop = QtGui.QIcon()
        icon_chev_stop.addPixmap(QtGui.QPixmap(os.path.join(icons_dir, "pause.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        
        self.joint_control_label = QtWidgets.QLabel(self.joint_control_large_frame)
        self.joint_control_label.setGeometry(QtCore.QRect(10, 5, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.joint_control_label.setFont(font)
        self.joint_control_label.setObjectName("joint_control_label")
        self.wheel_control_large_frame = QtWidgets.QFrame(self.centralwidget)
        self.wheel_control_large_frame.setGeometry(QtCore.QRect(1170, 50, 181, 341))
        self.wheel_control_large_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wheel_control_large_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wheel_control_large_frame.setObjectName("wheel_control_large_frame")
        self.wheel_control_label = QtWidgets.QLabel(self.wheel_control_large_frame)
        self.wheel_control_label.setGeometry(QtCore.QRect(10, 5, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.wheel_control_label.setFont(font)
        self.wheel_control_label.setObjectName("wheel_control_label")
        self.wheel_control_onoff_frame = QtWidgets.QFrame(self.wheel_control_large_frame)
        self.wheel_control_onoff_frame.setGeometry(QtCore.QRect(10, 30, 161, 61))
        self.wheel_control_onoff_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wheel_control_onoff_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wheel_control_onoff_frame.setObjectName("wheel_control_onoff_frame")
  
        icon_wheel_on = QtGui.QIcon()
        icon_wheel_on.addPixmap(QtGui.QPixmap(os.path.join(icons_dir,"power.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)  
        self.wheel_control_button = QtWidgets.QPushButton(self.wheel_control_onoff_frame)
        self.wheel_control_button.setGeometry(QtCore.QRect(5, 15, 30, 30))
        self.wheel_control_button.setObjectName("wheel_control_button")
        self.wheel_control_button.setObjectName("styleGroup1")
        self.wheel_control_button.setIcon(icon_wheel_on)
        self.wheel_control_button.setProperty("state","default")
        self.wheel_control_button.clicked.connect(lambda: self.toggleButtonStyle(self.wheel_control_button)) 
        
        self.wheel_control_front_button = QtWidgets.QPushButton(self.wheel_control_onoff_frame)
        self.wheel_control_front_button.setGeometry(QtCore.QRect(45,15,30,30))
        self.wheel_control_front_button.setText("")
        self.wheel_control_front_button.setIcon(icon_chev_up)
        self.wheel_control_front_button.setObjectName("wheel_control_front_button")
        self.wheel_control_front_button.setObjectName("styleGroup4")

                
        self.wheel_control_back_button = QtWidgets.QPushButton(self.wheel_control_onoff_frame)
        self.wheel_control_back_button.setGeometry(QtCore.QRect(85,15,30,30))
        self.wheel_control_back_button.setText("")
        self.wheel_control_back_button.setIcon(icon_chev_down)
        self.wheel_control_back_button.setObjectName("wheel_control_back_button")
        self.wheel_control_back_button.setObjectName("styleGroup4")
        
        
        self.wheel_control_stop_button = QtWidgets.QPushButton(self.wheel_control_onoff_frame)
        self.wheel_control_stop_button.setGeometry(QtCore.QRect(125,15,30,30))
        self.wheel_control_stop_button.setText("")
        self.wheel_control_stop_button.setIcon(icon_chev_stop)
        self.wheel_control_stop_button.setObjectName("wheel_control_stop_button")
        self.wheel_control_stop_button.setObjectName("styleGroup4")
        
        
        self.wheel_control_velocity_frame = QtWidgets.QFrame(self.wheel_control_large_frame)
        self.wheel_control_velocity_frame.setGeometry(QtCore.QRect(10, 98, 161, 41))
        self.wheel_control_velocity_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wheel_control_velocity_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wheel_control_velocity_frame.setObjectName("wheel_control_velocity_frame")
        self.wheel_velocity_label = QtWidgets.QLabel(self.wheel_control_velocity_frame)
        self.wheel_velocity_label.setGeometry(QtCore.QRect(10, 12, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.wheel_velocity_label.setFont(font)
        self.wheel_velocity_label.setObjectName("wheel_velocity_label")
        self.wheel_control_velocity_textedit = QtWidgets.QTextEdit(self.wheel_control_velocity_frame)
        self.wheel_control_velocity_textedit.setGeometry(QtCore.QRect(43, 8, 61, 25))
        self.wheel_control_velocity_textedit.setObjectName("wheel_control_velocity_textedit")
        
        self.wheel_velocity_set_button = QtWidgets.QPushButton(self.wheel_control_velocity_frame)
        self.wheel_velocity_set_button.setGeometry(QtCore.QRect(111, 8, 36, 25))
        self.wheel_velocity_set_button.setObjectName("wheel_velocity_set_button")
        self.wheel_velocity_set_button.setObjectName("styleGroup5")

        
        self.wheel_control_FL_frame = QtWidgets.QFrame(self.wheel_control_large_frame)
        self.wheel_control_FL_frame.setGeometry(QtCore.QRect(10, 146, 161, 41))
        self.wheel_control_FL_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wheel_control_FL_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wheel_control_FL_frame.setObjectName("wheel_control_FL_frame")
        self.FL_wheel_label = QtWidgets.QLabel(self.wheel_control_FL_frame)
        self.FL_wheel_label.setGeometry(QtCore.QRect(10, 12, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FL_wheel_label.setFont(font)
        self.FL_wheel_label.setObjectName("FL_wheel_label")
        

        
        self.wheel_control_FL_plus_button = QtWidgets.QPushButton(self.wheel_control_FL_frame)
        self.wheel_control_FL_plus_button.setGeometry(QtCore.QRect(79, 8, 31, 25))
        self.wheel_control_FL_plus_button.setText("")
        self.wheel_control_FL_plus_button.setIcon(icon_chev_up)
        self.wheel_control_FL_plus_button.setObjectName("wheel_control_FL_plus_button")
        self.wheel_control_FL_plus_button.setObjectName("styleGroup4")

        
        self.wheel_control_FL_minus_button = QtWidgets.QPushButton(self.wheel_control_FL_frame)
        self.wheel_control_FL_minus_button.setGeometry(QtCore.QRect(117, 8, 31, 25))
        self.wheel_control_FL_minus_button.setText("")
        self.wheel_control_FL_minus_button.setIcon(icon_chev_down)
        self.wheel_control_FL_minus_button.setObjectName("wheel_control_FL_minus_button")
        self.wheel_control_FL_minus_button.setObjectName("styleGroup4")        
        
        self.wheel_control_FL_icon_button = QtWidgets.QPushButton(self.wheel_control_FL_frame)
        self.wheel_control_FL_icon_button.setGeometry(QtCore.QRect(41, 8, 31, 25))
        self.wheel_control_FL_icon_button.setText("")
        self.wheel_control_FL_icon_button.setObjectName("styleGroup4")
        
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(os.path.join(icons_dir,"radio.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wheel_control_FL_icon_button.setIcon(icon6)
        self.wheel_control_FL_icon_button.setObjectName("wheel_control_FL_icon_button")
        self.wheel_control_FL_icon_button.setProperty("state","default")
        self.wheel_control_FL_icon_button.clicked.connect(lambda: self.toggleButtonStyle(self.wheel_control_FL_icon_button))        
        
        self.wheel_control_FR_frame = QtWidgets.QFrame(self.wheel_control_large_frame)
        self.wheel_control_FR_frame.setGeometry(QtCore.QRect(10, 194, 161, 41))
        self.wheel_control_FR_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wheel_control_FR_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wheel_control_FR_frame.setObjectName("wheel_control_FR_frame")
        self.FR_wheel_label = QtWidgets.QLabel(self.wheel_control_FR_frame)
        self.FR_wheel_label.setGeometry(QtCore.QRect(10, 10, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FR_wheel_label.setFont(font)
        self.FR_wheel_label.setObjectName("FR_wheel_label")
        self.wheel_control_FR_plus_button = QtWidgets.QPushButton(self.wheel_control_FR_frame)
        self.wheel_control_FR_plus_button.setGeometry(QtCore.QRect(79, 8, 31, 25))
        self.wheel_control_FR_plus_button.setText("")
        self.wheel_control_FR_plus_button.setIcon(icon_chev_up)
        self.wheel_control_FR_plus_button.setObjectName("wheel_control_FR_plus_button")
        self.wheel_control_FR_plus_button.setObjectName("styleGroup4")
        
        self.wheel_control_FR_minus_button = QtWidgets.QPushButton(self.wheel_control_FR_frame)
        self.wheel_control_FR_minus_button.setGeometry(QtCore.QRect(117, 8, 31, 25))
        self.wheel_control_FR_minus_button.setText("")
        self.wheel_control_FR_minus_button.setIcon(icon_chev_down)
        self.wheel_control_FR_minus_button.setObjectName("wheel_control_FR_minus_button")
        self.wheel_control_FR_minus_button.setObjectName("styleGroup4")
        
        self.wheel_control_FR_icon_button = QtWidgets.QPushButton(self.wheel_control_FR_frame)
        self.wheel_control_FR_icon_button.setGeometry(QtCore.QRect(41, 8, 31, 25))
        self.wheel_control_FR_icon_button.setText("")
        self.wheel_control_FR_icon_button.setIcon(icon6)
        self.wheel_control_FR_icon_button.setObjectName("wheel_control_FR_icon_button")
        self.wheel_control_FR_icon_button.setProperty("state","default")
        self.wheel_control_FR_icon_button.clicked.connect(lambda: self.toggleButtonStyle(self.wheel_control_RL_icon_button))        
        
        
        self.wheel_control_RL_frame = QtWidgets.QFrame(self.wheel_control_large_frame)
        self.wheel_control_RL_frame.setGeometry(QtCore.QRect(10, 242, 161, 41))
        self.wheel_control_RL_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wheel_control_RL_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wheel_control_RL_frame.setObjectName("wheel_control_RL_frame")
        self.RL_wheel_label = QtWidgets.QLabel(self.wheel_control_RL_frame)
        self.RL_wheel_label.setGeometry(QtCore.QRect(10, 12, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RL_wheel_label.setFont(font)
        self.RL_wheel_label.setObjectName("RL_wheel_label")
        self.wheel_control_RL_plus_button = QtWidgets.QPushButton(self.wheel_control_RL_frame)
        self.wheel_control_RL_plus_button.setGeometry(QtCore.QRect(79, 10, 31, 25))
        self.wheel_control_RL_plus_button.setText("")
        self.wheel_control_RL_plus_button.setIcon(icon_chev_up)
        self.wheel_control_RL_plus_button.setObjectName("wheel_control_RL_plus_button")
        self.wheel_control_RL_plus_button.setObjectName("styleGroup4")
        
        self.wheel_control_RL_minus_button = QtWidgets.QPushButton(self.wheel_control_RL_frame)
        self.wheel_control_RL_minus_button.setGeometry(QtCore.QRect(117, 10, 31, 25))
        self.wheel_control_RL_minus_button.setText("")
        self.wheel_control_RL_minus_button.setIcon(icon_chev_down)
        self.wheel_control_RL_minus_button.setObjectName("wheel_control_RL_minus_button")
        self.wheel_control_RL_minus_button.setObjectName("styleGroup4")
        
        self.wheel_control_RL_icon_button = QtWidgets.QPushButton(self.wheel_control_RL_frame)
        self.wheel_control_RL_icon_button.setGeometry(QtCore.QRect(41, 10, 31, 25))
        self.wheel_control_RL_icon_button.setText("")
        self.wheel_control_RL_icon_button.setIcon(icon6)
        self.wheel_control_RL_icon_button.setObjectName("wheel_control_RL_icon_button")
        self.wheel_control_RL_icon_button.setProperty("state","default")
        self.wheel_control_RL_icon_button.clicked.connect(lambda: self.toggleButtonStyle(self.wheel_control_RL_icon_button))        
        
        
        
        self.wheel_control_RR_frame = QtWidgets.QFrame(self.wheel_control_large_frame)
        self.wheel_control_RR_frame.setGeometry(QtCore.QRect(10, 290, 161, 41))
        self.wheel_control_RR_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wheel_control_RR_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wheel_control_RR_frame.setObjectName("wheel_control_RR_frame")
        self.RR_wheel_label = QtWidgets.QLabel(self.wheel_control_RR_frame)
        self.RR_wheel_label.setGeometry(QtCore.QRect(10, 12, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RR_wheel_label.setFont(font)
        self.RR_wheel_label.setObjectName("RR_wheel_label")
        self.wheel_control_RR_plus_button = QtWidgets.QPushButton(self.wheel_control_RR_frame)
        self.wheel_control_RR_plus_button.setGeometry(QtCore.QRect(79, 8, 31, 25))
        self.wheel_control_RR_plus_button.setText("")
        self.wheel_control_RR_plus_button.setIcon(icon_chev_up)
        self.wheel_control_RR_plus_button.setObjectName("wheel_control_RR_plus_button")
        self.wheel_control_RR_plus_button.setObjectName("styleGroup4")
        
        self.wheel_control_RR_minus_button = QtWidgets.QPushButton(self.wheel_control_RR_frame)
        self.wheel_control_RR_minus_button.setGeometry(QtCore.QRect(117, 8, 31, 25))
        self.wheel_control_RR_minus_button.setText("")
        self.wheel_control_RR_minus_button.setIcon(icon_chev_down)
        self.wheel_control_RR_minus_button.setObjectName("wheel_control_RR_minus_button")
        self.wheel_control_RR_minus_button.setObjectName("styleGroup4")
        
        self.wheel_control_RR_icon_button = QtWidgets.QPushButton(self.wheel_control_RR_frame)
        self.wheel_control_RR_icon_button.setGeometry(QtCore.QRect(41, 8, 31, 25))
        self.wheel_control_RR_icon_button.setText("")
        self.wheel_control_RR_icon_button.setIcon(icon6)
        self.wheel_control_RR_icon_button.setObjectName("wheel_control_RR_icon_button")
        self.wheel_control_RR_icon_button.setProperty("state","default")
        self.wheel_control_RR_icon_button.clicked.connect(lambda: self.toggleButtonStyle(self.wheel_control_RR_icon_button))        
        
        
        self.system_log_frame = QtWidgets.QFrame(self.centralwidget)
        self.system_log_frame.setGeometry(QtCore.QRect(0, 395, 731, 126))
        self.system_log_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.system_log_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.system_log_frame.setObjectName("system_log_frame")
        self.system_log_label = QtWidgets.QLabel(self.system_log_frame)
        self.system_log_label.setGeometry(QtCore.QRect(10, 5, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.system_log_label.setFont(font)
        self.system_log_label.setObjectName("system_log_label")
        
        
        self.system_log_browser = QtWidgets.QTextBrowser(self.system_log_frame)
        self.system_log_browser.setGeometry(QtCore.QRect(10, 25, 711, 90))
        self.system_log_browser.setObjectName("system_log_browser")
        self.system_log_browser.setReadOnly(True)
        
        self.pose_control_large_frame = QtWidgets.QFrame(self.centralwidget)
        self.pose_control_large_frame.setGeometry(QtCore.QRect(735, 395, 431, 126))
        self.pose_control_large_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pose_control_large_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pose_control_large_frame.setObjectName("pose_control_large_frame")

        self.pose_control_label = QtWidgets.QLabel(self.pose_control_large_frame)
        self.pose_control_label.setGeometry(QtCore.QRect(10, 5, 211, 21))
        self.pose_control_label.setFont(font)
        self.pose_control_label.setObjectName("pose_control_label")

        # dx
        self.dx_label = QtWidgets.QLabel(self.pose_control_large_frame)
        self.dx_label.setGeometry(QtCore.QRect(10, 50, 21, 16))
        self.dx_label.setFont(font)
        self.dx_label.setObjectName("dx_label")
        self.pose_control_dx_textedit = NoTabTextEdit(self.pose_control_large_frame)
        self.pose_control_dx_textedit.setGeometry(QtCore.QRect(40, 50, 71, 28))
        self.pose_control_dx_textedit.setObjectName("pose_control_dx_textedit")

        # dy
        self.dy_label = QtWidgets.QLabel(self.pose_control_large_frame)
        self.dy_label.setGeometry(QtCore.QRect(130, 50, 21, 16))
        self.dy_label.setFont(font)
        self.dy_label.setObjectName("dy_label")
        self.pose_control_dy_textedit = NoTabTextEdit(self.pose_control_large_frame)
        self.pose_control_dy_textedit.setGeometry(QtCore.QRect(160, 50, 71, 28))
        self.pose_control_dy_textedit.setObjectName("pose_control_dy_textedit")

        # dz
        self.dz_label = QtWidgets.QLabel(self.pose_control_large_frame)
        self.dz_label.setGeometry(QtCore.QRect(250, 50, 21, 16))
        self.dz_label.setFont(font)
        self.dz_label.setObjectName("dz_label")
        self.pose_control_dz_textedit = NoTabTextEdit(self.pose_control_large_frame)
        self.pose_control_dz_textedit.setGeometry(QtCore.QRect(280, 50, 71, 28))
        self.pose_control_dz_textedit.setObjectName("pose_control_dz_textedit")

        # set button
        self.set_button = QtWidgets.QPushButton(self.pose_control_large_frame)
        self.set_button.setGeometry(QtCore.QRect(370, 50, 51, 28))
        self.set_button.setObjectName("set_button")
        self.set_button.setObjectName("styleGroup5")
        
        
        self.test_buttons_frame = QtWidgets.QFrame(self.centralwidget)
        self.test_buttons_frame.setGeometry(QtCore.QRect(1170, 395, 181, 126))
        self.test_buttons_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.test_buttons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.test_buttons_frame.setObjectName("test_buttons_frame")
        self.test_buttons_label = QtWidgets.QLabel(self.test_buttons_frame)
        self.test_buttons_label.setGeometry(QtCore.QRect(10, 5, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.test_buttons_label.setFont(font)
        self.test_buttons_label.setObjectName("test_buttons_label")
        self.test_1_button = QtWidgets.QPushButton(self.test_buttons_frame)
        self.test_1_button.setGeometry(QtCore.QRect(10, 30, 80, 23))
        self.test_1_button.setObjectName("test_1_button")
        self.test_2_button = QtWidgets.QPushButton(self.test_buttons_frame)
        self.test_2_button.setGeometry(QtCore.QRect(10, 60, 80, 23))
        self.test_2_button.setObjectName("test_2_button")
        self.test_3_button = QtWidgets.QPushButton(self.test_buttons_frame)
        self.test_3_button.setGeometry(QtCore.QRect(10, 90, 80, 23))
        self.test_3_button.setObjectName("test_3_button")
        self.test_4_button = QtWidgets.QPushButton(self.test_buttons_frame)
        self.test_4_button.setGeometry(QtCore.QRect(95, 30, 80, 23))
        self.test_4_button.setObjectName("test_4_button")
        self.test_5_button = QtWidgets.QPushButton(self.test_buttons_frame)
        self.test_5_button.setGeometry(QtCore.QRect(95, 60, 80, 23))
        self.test_5_button.setObjectName("test_5_button")
        self.test_6_button = QtWidgets.QPushButton(self.test_buttons_frame)
        self.test_6_button.setGeometry(QtCore.QRect(95, 90, 80, 23))
        self.test_6_button.setObjectName("test_6_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.robot_controller_ui_title_label.setText(_translate("MainWindow", "ROBOT CONTROLLER UI"))
        self.activation_robot2_button.setText(_translate("MainWindow", "robot2"))
        self.activation_joint_button.setText(_translate("MainWindow", "Joint"))
        self.activation_all_button.setText(_translate("MainWindow", "All"))
        self.activation_label.setText(_translate("MainWindow", "Activation"))
        self.calibration_wheel_button.setText(_translate("MainWindow", "Wheel"))
        self.calibration_joint_button.setText(_translate("MainWindow", "Joint"))
        self.calibration_robot2_button.setText(_translate("MainWindow", "robot2"))
        self.calibration_all_button.setText(_translate("MainWindow", "All"))
        self.calibration_label.setText(_translate("MainWindow", "Calibration"))
        self.robot2_control_label.setText(_translate("MainWindow", "robot2 Control"))
        self.robot2_control_both_label.setText(_translate("MainWindow", "Both"))
        self.robot2_control_left_label.setText(_translate("MainWindow", "Left"))
        self.robot2_control_right_label.setText(_translate("MainWindow", "Right"))
        self.land_button.setText(_translate("MainWindow", "Land"))
        self.stand_button.setText(_translate("MainWindow", "Stand"))
        self.default_button.setText(_translate("MainWindow", "Default"))
        self.posture_A_button.setText(_translate("MainWindow", "Pos A"))
        self.posture_B_button.setText(_translate("MainWindow", "Pos B"))
        self.robot2_remote_control_label.setText(_translate("MainWindow", "robot2 remote controller"))
        self.robot2_wheel_leg_control_label.setText(_translate("MainWindow", "robot1 remote controller"))
        self.joint_control_FL_label.setText(_translate("MainWindow", "FL"))
        self.joint_control_FL_x_set_button.setText(_translate("MainWindow", "set"))
        self.joint_control_FL_y_set_button.setText(_translate("MainWindow", "set"))
        self.joint_control_FL_z_set_button.setText(_translate("MainWindow", "set"))
        self.joint_control_FR_labal.setText(_translate("MainWindow", "FR"))
        self.joint_control_FR_z_set_button.setText(_translate("MainWindow", "set"))
        self.joint_control_FR_x_set_button.setText(_translate("MainWindow", "set"))
        self.joint_control_FR_y_set_button.setText(_translate("MainWindow", "set"))
        self.joint_control_RL_label.setText(_translate("MainWindow", "RL"))
        self.joint_control_RL_z_set_button.setText(_translate("MainWindow", "set"))
        self.joint_control_RL_x_set_button.setText(_translate("MainWindow", "set"))
        self.joint_control_RL_y_set_button.setText(_translate("MainWindow", "set"))
        self.joint_control_RR_label.setText(_translate("MainWindow", "RR"))
        self.joint_control_RR_z_set_button.setText(_translate("MainWindow", "set"))
        self.joint_control_RR_x_set_button.setText(_translate("MainWindow", "set"))
        self.joint_control_RR_y_set_button.setText(_translate("MainWindow", "set"))
        self.joint_control_label.setText(_translate("MainWindow", "Joint control"))
        self.wheel_control_label.setText(_translate("MainWindow", "Wheel control"))
        self.wheel_velocity_label.setText(_translate("MainWindow", "Vel."))
        self.wheel_velocity_set_button.setText(_translate("MainWindow", "set"))
        self.FL_wheel_label.setText(_translate("MainWindow", "FL"))
        self.FR_wheel_label.setText(_translate("MainWindow", "FR"))
        self.RL_wheel_label.setText(_translate("MainWindow", "RL"))
        self.RR_wheel_label.setText(_translate("MainWindow", "RR"))
        self.system_log_label.setText(_translate("MainWindow", "System log"))
        self.pose_control_label.setText(_translate("MainWindow", "Pose control"))

        self.dx_label.setText(_translate("MainWindow", "dx"))
        self.dy_label.setText(_translate("MainWindow", "dy"))
        self.dz_label.setText(_translate("MainWindow", "dz"))
        self.set_button.setText(_translate("MainWindow", "Set"))
        self.test_buttons_label.setText(_translate("MainWindow", "Test buttons"))
        self.test_1_button.setText(_translate("MainWindow", "Test-1"))
        self.test_2_button.setText(_translate("MainWindow", "Test-2"))
        self.test_3_button.setText(_translate("MainWindow", "Test-3"))
        self.test_4_button.setText(_translate("MainWindow", "Test-4"))
        self.test_5_button.setText(_translate("MainWindow", "Test-5"))
        self.test_6_button.setText(_translate("MainWindow", "Test-6"))
        
        #aa
        

    def toggleButtonStyle(self, button):
        current_state = button.property("state")
        
        if current_state == "default":
            button.setStyleSheet("background-color: green;")  # True state color
            button.setProperty("state", "true")
            print("default -> true")
        elif current_state == "true":
            button.setStyleSheet("background-color: #fa4949;")  # False state color
            button.setProperty("state", "false")
            print("true -> false")
        elif current_state == "false":
            button.setStyleSheet("background-color: green;")  # Default state color
            button.setProperty("state", "true")
            print("false -> true")

        button.style().unpolish(button)  # Refresh the style
        button.style().polish(button)
        

            
            

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(window)
    sys.exit(app.exec_())
